import org.springframework.boot.gradle.tasks.bundling.BootJar

plugins {
	id 'java'
	id 'org.springframework.boot' version "${springBootVersion}"
	id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
}

allprojects {
	group = "${projectGroup}"
	version = "${applicationVersion}"

	repositories {
		mavenCentral()
	}

	sourceCompatibility = project.javaVersion
	targetCompatibility = project.javaVersion

	dependencyManagement {
		imports {
			mavenBom "io.awspring.cloud:spring-cloud-aws-dependencies:3.3.0"
		}
	}
}

subprojects {
	apply plugin: 'java-library'
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'

	dependencies {
		implementation 'org.springframework.boot:spring-boot-starter'

		//AWS
		implementation "io.awspring.cloud:spring-cloud-aws-starter"
		implementation "io.awspring.cloud:spring-cloud-aws-starter-s3"
		implementation 'io.awspring.cloud:spring-cloud-aws-starter-parameter-store'

		// TEST
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
		testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	}

	tasks.withType(Test) {
		test.useJUnitPlatform()
	}

	tasks.withType(BootJar) {
		enabled = project.name == 'bootstrap-module' || project.name == 'socket-module'
	}

	tasks.withType(Jar) {
		enabled = project.name != 'bootstrap-module'
	}
}